---
- name: Install and run Redis using Docker
  hosts: servers
  remote_user: root
  vars:
    redis_password: "pass"
  pre_tasks:
    - name: Check if Docker service is enabled
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
  tasks:
    - name: Install Redis
      docker_container:
        name: redis
        image: redis:latest
        env:
          - REDIS_PASSWORD: "{{ redis_password }}"
        ports:
          - "6379:6379"
        state: started
      become: yes